# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import booking_pb2 as booking__pb2


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Booking = channel.unary_unary(
                '/restaurantbooking.BookingService/Booking',
                request_serializer=booking__pb2.BookingRequest.SerializeToString,
                response_deserializer=booking__pb2.BookingReply.FromString,
                )


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Booking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Booking': grpc.unary_unary_rpc_method_handler(
                    servicer.Booking,
                    request_deserializer=booking__pb2.BookingRequest.FromString,
                    response_serializer=booking__pb2.BookingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurantbooking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Booking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/restaurantbooking.BookingService/Booking',
            booking__pb2.BookingRequest.SerializeToString,
            booking__pb2.BookingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
