apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        # match with service's selector  
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: jeffreyyap977/python-flask:latest
        ports:
        - containerPort: 5000 

