apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  type: LoadBalancer
  selector:
    # match with deployment's labels 
    app: my-flask-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80

  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 5000
  # type: LoadBalancer
